[connection]
url = "oracle-linux.apa-canal.md:1521/ACC"
credentials = { user = "FOUNDATION", pw = "FOUNDATION_PASSWORD"}

[jwt]
public-key = "keyring/jwt-public-key.pem"
issuer = "https://sia.acc.md/using-jwt-rbac"

[others]
excludes = ["COPIE"]
